name: Publish master
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.x

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile and test
        run: ./gradlew build --info

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: tzarsmango/memento-user
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}